/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    SimpleIcon icon = new SimpleIcon(150,150);

    public static void main(String[] args) {
        GUI gui = new GUI();
    }
}
